"""Add WorkLog model

Revision ID: 0cfa91c41dd3
Revises: e95242e5fa7b
Create Date: 2025-04-11 17:10:47.671064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfa91c41dd3'
down_revision = 'e95242e5fa7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worklogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('work_order', sa.String(length=50), nullable=True),
    sa.Column('part_number', sa.String(length=50), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worklogs')
    # ### end Alembic commands ###
