"""add default_unit to users

Revision ID: 1cb167a10742
Revises: c27145800364
Create Date: 2025-04-30 13:46:02.893893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb167a10742'
down_revision = 'c27145800364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint('chat_messages_permission_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_permissions', ['permission_id'], ['id'])

    with op.batch_alter_table('unit_work_types', schema=None) as batch_op:
        batch_op.drop_constraint('unit_work_types_unit_id_work_type_id_key', type_='unique')
        batch_op.create_unique_constraint('uq_unit_work_type', ['unit_id', 'work_type_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_unit', sa.String(length=100), nullable=True))

    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.alter_column('edit_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='編集理由',
               existing_nullable=True)
        batch_op.alter_column('original_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='編集元の工数ID（申請時に使用）',
               existing_nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worklogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('original_id',
               existing_type=sa.INTEGER(),
               comment='編集元の工数ID（申請時に使用）',
               existing_nullable=True)
        batch_op.alter_column('edit_reason',
               existing_type=sa.TEXT(),
               comment='編集理由',
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_unit')

    with op.batch_alter_table('unit_work_types', schema=None) as batch_op:
        batch_op.drop_constraint('uq_unit_work_type', type_='unique')
        batch_op.create_unique_constraint('unit_work_types_unit_id_work_type_id_key', ['unit_id', 'work_type_id'])

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_messages_permission_id_fkey', 'chat_permissions', ['permission_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
