"""Add chat_messages table

Revision ID: c27145800364
Revises: c3a037e2f571
Create Date: 2025-04-15 16:44:35.791913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c27145800364'
down_revision = 'c3a037e2f571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主キー',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='チャット許可ID (chat_permissionsテーブルの外部キー)',
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='送信者ID (usersテーブルの外部キー)',
               existing_nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='受信者ID (usersテーブルの外部キー)',
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='メッセージ本文',
               existing_nullable=False)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='既読フラグ (true: 既読, false: 未読)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='更新日時',
               existing_nullable=True)
        batch_op.drop_index('idx_chat_messages_created_at')
        batch_op.drop_index('idx_chat_messages_permission')
        batch_op.drop_index('idx_chat_messages_receiver')
        batch_op.drop_index('idx_chat_messages_sender')
        batch_op.drop_constraint('fk_permission', type_='foreignkey')
        batch_op.drop_constraint('fk_receiver', type_='foreignkey')
        batch_op.drop_constraint('fk_sender', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat_permissions', ['permission_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='チャットメッセージ保存テーブル'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_table_comment(
        'チャットメッセージ保存テーブル',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_sender', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_receiver', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_permission', 'chat_permissions', ['permission_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_chat_messages_sender', ['sender_id'], unique=False)
        batch_op.create_index('idx_chat_messages_receiver', ['receiver_id'], unique=False)
        batch_op.create_index('idx_chat_messages_permission', ['permission_id'], unique=False)
        batch_op.create_index('idx_chat_messages_created_at', ['created_at'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='更新日時',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='作成日時',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               comment='既読フラグ (true: 既読, false: 未読)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               comment='メッセージ本文',
               existing_nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               comment='受信者ID (usersテーブルの外部キー)',
               existing_nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               comment='送信者ID (usersテーブルの外部キー)',
               existing_nullable=False)
        batch_op.alter_column('permission_id',
               existing_type=sa.INTEGER(),
               comment='チャット許可ID (chat_permissionsテーブルの外部キー)',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               comment='主キー',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
